return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "left-down",
  width = 256,
  height = 256,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 76,
  nextobjectid = 2045,
  properties = {},
  tilesets = {
    {
      name = "imgs",
      firstgid = 1,
      class = "",
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "imgs2",
      firstgid = 1,
      class = "",
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "xgame_bg",
      firstgid = 1,
      class = "",
      tilewidth = 565,
      tileheight = 513,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 11,
      tiles = {
        {
          id = 1,
          image = "gfx/levelA01.png",
          width = 512,
          height = 440
        },
        {
          id = 2,
          image = "gfx/levelA10.png",
          width = 359,
          height = 256
        },
        {
          id = 3,
          image = "gfx/levelA11.png",
          width = 324,
          height = 513
        },
        {
          id = 4,
          image = "gfx/levelA12.png",
          width = 380,
          height = 476
        },
        {
          id = 5,
          image = "gfx/levelA13.png",
          width = 254,
          height = 418
        },
        {
          id = 6,
          image = "gfx/levelA14.png",
          width = 565,
          height = 318
        },
        {
          id = 7,
          image = "gfx/levelA15.png",
          width = 111,
          height = 161
        },
        {
          id = 8,
          image = "gfx/levelA16.png",
          width = 437,
          height = 260
        },
        {
          id = 9,
          image = "gfx/levelA17.png",
          width = 416,
          height = 264
        },
        {
          id = 10,
          image = "gfx/levelA18.png",
          width = 275,
          height = 251
        },
        {
          id = 11,
          image = "gfx/levelA19.png",
          width = 162,
          height = 104
        }
      }
    },
    {
      name = "imgs3",
      firstgid = 13,
      class = "",
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "imgs4",
      firstgid = 13,
      class = "",
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "xgame_fg",
      firstgid = 13,
      class = "",
      tilewidth = 255,
      tileheight = 430,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 4,
      tiles = {
        {
          id = 0,
          image = "gfx/levelA_fg01.png",
          width = 255,
          height = 430
        },
        {
          id = 1,
          image = "gfx/levelA_fg02.png",
          width = 150,
          height = 318
        },
        {
          id = 2,
          image = "gfx/levelA_fg03.png",
          width = 120,
          height = 62
        },
        {
          id = 3,
          image = "gfx/levelA_fg04.png",
          width = 20,
          height = 32
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 25,
      name = "bg_deco_shapes_sky",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 70, 209 },
      properties = {},
      objects = {
        {
          id = 1093,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2528,
          y = 3840,
          width = 1024,
          height = 576,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1236,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3552,
          y = 3840,
          width = 1024,
          height = 576,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1237,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4576,
          y = 3840,
          width = 1024,
          height = 576,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1253,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5600,
          y = 3840,
          width = 1024,
          height = 576,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 57,
      name = "bg_deco_shapes_shadows",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 65,
      name = "bg_deco_shapes_lights",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 55,
      name = "bg_deco_shapes02",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 56,
      name = "bg_deco_shapes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "group",
      id = 73,
      name = "***DECO OTHERS***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 71,
      name = "bg_deco_images_finalx",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2031,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2528,
          y = 4269,
          width = 359,
          height = 256,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 2032,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3056,
          y = 4369,
          width = 324,
          height = 513,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 2033,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3380,
          y = 4372,
          width = 380,
          height = 476,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 2034,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3760,
          y = 4372,
          width = 254,
          height = 418,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 2035,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4032,
          y = 4368,
          width = 565,
          height = 318,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 2036,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4456,
          y = 4122,
          width = 111,
          height = 161,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 2037,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4624,
          y = 4281,
          width = 437,
          height = 260,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 2038,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5096,
          y = 4272,
          width = 416,
          height = 264,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 2039,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5512,
          y = 4272,
          width = 275,
          height = 251,
          rotation = 0,
          gid = 11,
          visible = true,
          properties = {}
        },
        {
          id = 2040,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5791,
          y = 4296,
          width = 162,
          height = 104,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 58,
      name = "bg_deco_images_final",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2029,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2016,
          y = 4264,
          width = 512,
          height = 440,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 75,
      name = "fg_deco_images_finalx",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2041,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2136,
          y = 4264,
          width = 255,
          height = 430,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 2042,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3088,
          y = 4368,
          width = 150,
          height = 318,
          rotation = 0,
          gid = 14,
          visible = true,
          properties = {}
        },
        {
          id = 2043,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3432,
          y = 4368,
          width = 120,
          height = 62,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 2044,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3952,
          y = 4368,
          width = 20,
          height = 32,
          rotation = 0,
          gid = 16,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 74,
      name = "fg_deco_images_final",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "group",
      id = 72,
      name = "***DECO FINAL***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 66,
      name = "bg_deco_images04x",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 67,
      name = "bg_deco_images04",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 42,
      name = "bg_deco_images03x",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 63,
      name = "bg_deco_images03",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 64,
      name = "bg_deco_images02x",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 41,
      name = "bg_deco_images02",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 69,
      name = "bg_deco_imagesx",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 29,
      name = "bg_deco_images",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 32,
      name = "bg_deco_texts",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 255, 0 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 28,
      name = "fg_deco_shapes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 255, 255 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 60,
      name = "fg_deco_images03",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 59,
      name = "fg_deco_images02",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 70,
      name = "fg_deco_imagesx",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 30,
      name = "fg_deco_images",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 33,
      name = "fg_deco_texts",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 255, 0 },
      properties = {},
      objects = {
        {
          id = 1106,
          name = "",
          type = "",
          shape = "text",
          x = 5952,
          y = 4184,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          text = "EXIT",
          fontfamily = "Segoe UI",
          pixelsize = 17,
          wrap = true,
          halign = "center",
          valign = "center",
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 48,
      name = "***DECO***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 24,
      name = "physics_players",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 0, 0 },
      properties = {},
      objects = {
        {
          id = 654,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2048,
          y = 3896,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 52,
      name = "physics_ground_nmes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1377,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3904,
          y = 4304,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1382,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3616,
          y = 4197,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 19,
      name = "physics_ground_nmes02",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 0, 0 },
      properties = {},
      objects = {
        {
          id = 1208,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4368,
          y = 4304,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1251,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4680,
          y = 4056,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1254,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3720,
          y = 4304,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1255,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3512,
          y = 4304,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1263,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5760,
          y = 4128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1285,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 4208,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 47,
      name = "physics_ground_nmes03",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1287,
          name = "lives",
          type = "",
          shape = "rectangle",
          x = 4240,
          y = 3960,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1290,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4432,
          y = 4224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1291,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5176,
          y = 4208,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1300,
          name = "lives",
          type = "",
          shape = "rectangle",
          x = 5536,
          y = 4128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1364,
          name = "kdoorBb",
          type = "",
          shape = "rectangle",
          x = 3936,
          y = 4195,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 54,
      name = "physics_ground_nmes04",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1378,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4896,
          y = 4056,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1379,
          name = "kdoorCc",
          type = "",
          shape = "rectangle",
          x = 5408,
          y = 4208,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1380,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5696,
          y = 4128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1385,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5024,
          y = 4208,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 23,
      name = "physics_flying_nmes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 85, 0 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 39,
      name = "physics_turret_nmes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 85, 0 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 43,
      name = "physics_breakables",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "group",
      id = 49,
      name = "***PHYSICS_ACTORS***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 21,
      name = "physics_lives",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 170, 0 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 20,
      name = "physics_coins",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 170, 0 },
      properties = {},
      objects = {
        {
          id = 869,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2264,
          y = 4080,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1047,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2304,
          y = 4216,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1049,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2368,
          y = 4216,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2136,
          y = 4080,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1173,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2200,
          y = 4080,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1375,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3200,
          y = 4184,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1383,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3624,
          y = 4096,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 38,
      name = "physics_keys",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 170, 127 },
      properties = {},
      objects = {
        {
          id = 1160,
          name = "kdoorAa",
          type = "",
          shape = "rectangle",
          x = 2336,
          y = 4216,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 50,
      name = "***PHYSICS_COLLECTIBLES***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 61,
      name = "physics_grounds02",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1779,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 3840,
          width = 32,
          height = 424,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1780,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2096,
          y = 4120,
          width = 376,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1781,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2496,
          y = 4144,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1782,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2504,
          y = 3840,
          width = 24,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1783,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2016,
          y = 3976,
          width = 376,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1784,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2256,
          y = 3840,
          width = 24,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1785,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2472,
          y = 3976,
          width = 56,
          height = 168,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1786,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 3808,
          width = 544,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1789,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 4264,
          width = 560,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "physics_grounds",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 53, 53, 53 },
      properties = {},
      objects = {
        {
          id = 651,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2528,
          y = 3808,
          width = 3456,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 722,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2544,
          y = 4264,
          width = 368,
          height = 112,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1215,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 4376,
          width = 4000,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1219,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4000,
          y = 3840,
          width = 48,
          height = 440,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1224,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 4288,
          width = 128,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1227,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4448,
          y = 4120,
          width = 176,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1228,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4576,
          y = 3888,
          width = 48,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1232,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4576,
          y = 4144,
          width = 48,
          height = 232,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1243,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4896,
          y = 4120,
          width = 224,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1244,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4968,
          y = 3840,
          width = 152,
          height = 280,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1245,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5088,
          y = 4136,
          width = 32,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1250,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4624,
          y = 4272,
          width = 688,
          height = 104,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1252,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5920,
          y = 3840,
          width = 64,
          height = 344,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1283,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4048,
          y = 3840,
          width = 920,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1289,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4624,
          y = 4216,
          width = 192,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1299,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5520,
          y = 4200,
          width = 272,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1370,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4192,
          y = 4024,
          width = 128,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1384,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3836,
          y = 4259,
          width = 164,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1390,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5952,
          y = 4184,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1794,
          name = "a",
          type = "",
          shape = "rectangle",
          x = 2976,
          y = 4368,
          width = 1440,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1837,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 4272,
          width = 560,
          height = 104,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1862,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2880,
          y = 4160,
          width = 32,
          height = 104,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1885,
          name = "a",
          type = "",
          shape = "rectangle",
          x = 2912,
          y = 4264,
          width = 64,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1886,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2912,
          y = 4272,
          width = 64,
          height = 104,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1895,
          name = "a",
          type = "",
          shape = "rectangle",
          x = 4544,
          y = 4368,
          width = 32,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1996,
          name = "a",
          type = "",
          shape = "rectangle",
          x = 5312,
          y = 4272,
          width = 208,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1997,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5312,
          y = 4280,
          width = 208,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1998,
          name = "a",
          type = "",
          shape = "rectangle",
          x = 5520,
          y = 4192,
          width = 272,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1999,
          name = "a",
          type = "",
          shape = "rectangle",
          x = 5792,
          y = 4272,
          width = 160,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2001,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5792,
          y = 4280,
          width = 192,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 62,
      name = "physics_ptpfs02",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1787,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2016,
          y = 4120,
          width = 80,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1788,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2392,
          y = 3976,
          width = 80,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "physics_ptpfs",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 85, 255 },
      properties = {},
      objects = {
        {
          id = 1239,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4048,
          y = 4136,
          width = 136,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1240,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4320,
          y = 4128,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1241,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4048,
          y = 4216,
          width = 320,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1242,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4624,
          y = 4120,
          width = 272,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1758,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3072,
          y = 4249,
          width = 282,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1761,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3073,
          y = 4093,
          width = 274,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1762,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3384,
          y = 4261,
          width = 354,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "physics_steps",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 79, 238 },
      properties = {},
      objects = {
        {
          id = 1369,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4448,
          y = 4124,
          width = 4,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 22,
      name = "physics_walls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 255, 0 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "physics_ladders",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 71, 71, 213 },
      properties = {},
      objects = {
        {
          id = 739,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2408,
          y = 3976,
          width = 48,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 864,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2024,
          y = 4120,
          width = 56,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 17,
      name = "physics_mvpfs",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 85, 127 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 35,
      name = "physics_ptmvpfs",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 85, 127 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "physics_springs",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 170, 127 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 44,
      name = "physics_door_sensors",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 170, 255 },
      properties = {},
      objects = {
        {
          id = 1116,
          name = "kdoorZ1",
          type = "",
          shape = "rectangle",
          x = 2160,
          y = 3840,
          width = 208,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1118,
          name = "kdoorAa",
          type = "",
          shape = "rectangle",
          x = 2400,
          y = 4144,
          width = 224,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2368,
          y = 3840,
          width = 8,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2152,
          y = 3840,
          width = 8,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2392,
          y = 4144,
          width = 8,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2624,
          y = 4072,
          width = 8,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1221,
          name = "kdoorBb",
          type = "",
          shape = "rectangle",
          x = 3904,
          y = 4280,
          width = 256,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1367,
          name = "kdoorBb",
          type = "",
          shape = "rectangle",
          x = 4048,
          y = 4224,
          width = 112,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1222,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4160,
          y = 4224,
          width = 8,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1223,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3896,
          y = 4280,
          width = 8,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1246,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5230,
          y = 4136,
          width = 8,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1247,
          name = "kdoorZ3",
          type = "",
          shape = "rectangle",
          x = 4990,
          y = 4136,
          width = 240,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1249,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4982,
          y = 4136,
          width = 8,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1365,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3896,
          y = 4272,
          width = 40,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1366,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3928,
          y = 4128,
          width = 8,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1368,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4048,
          y = 4216,
          width = 120,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1387,
          name = "kdoorCc",
          type = "",
          shape = "rectangle",
          x = 5792,
          y = 3840,
          width = 128,
          height = 432,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1388,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5784,
          y = 3840,
          width = 8,
          height = 352,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 37,
      name = "physics_doorsB",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 64, 62, 43 },
      properties = {},
      objects = {
        {
          id = 1220,
          name = "kdoorBbx0y72",
          type = "",
          shape = "rectangle",
          x = 4012,
          y = 4272,
          width = 24,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1248,
          name = "kdoorZ3x0y72",
          type = "",
          shape = "rectangle",
          x = 5094,
          y = 4176,
          width = 20,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1389,
          name = "kdoorCcx0y72",
          type = "",
          shape = "rectangle",
          x = 5920,
          y = 4176,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 68,
      name = "physics_doors",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1893,
          name = "kdoorZ1x0y72",
          type = "",
          shape = "rectangle",
          x = 2256,
          y = 3888,
          width = 24,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1894,
          name = "kdoorAax0y72",
          type = "",
          shape = "rectangle",
          x = 2500,
          y = 4168,
          width = 24,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 40,
      name = "physics_spikes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 255, 0, 0, 5 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 27,
      name = "physics_voids",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 0, 255 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 31,
      name = "physics_exits",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 255, 255, 0 },
      properties = {},
      objects = {
        {
          id = 707,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5952,
          y = 4184,
          width = 16,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 46,
      name = "physics_invisible_blocks",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 255, 170, 255 },
      properties = {},
      objects = {
        {
          id = 1266,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4528,
          y = 4144,
          width = 48,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1267,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4448,
          y = 3888,
          width = 48,
          height = 232,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1268,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5584,
          y = 3840,
          width = 48,
          height = 352,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1295,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3056,
          y = 3840,
          width = 48,
          height = 528,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1296,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4032,
          y = 4256,
          width = 16,
          height = 112,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1297,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5080,
          y = 4144,
          width = 48,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 51,
      name = "***PHYSICS_WORLD***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 45,
      name = "physics_map_def",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1172,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 3808,
          width = 4000,
          height = 608,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 53,
      name = "***REFS***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 26,
          name = "physics_mvpfs_REFS",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          tintcolor = { 255, 255, 255 },
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 36,
          name = "level_design_REFS",
          class = "",
          visible = false,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 868,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1944,
              y = 3808,
              width = 32,
              height = 448,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1150,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1984,
              y = 3768,
              width = 544,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1282,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2016,
              y = 4120,
              width = 40,
              height = 144,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1288,
              name = "jump_height",
              type = "",
              shape = "rectangle",
              x = 3416,
              y = 4152,
              width = 32,
              height = 112,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1348,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2584,
              y = 3808,
              width = 128,
              height = 560,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1360,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2016,
              y = 3840,
              width = 40,
              height = 136,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1362,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2016,
              y = 3976,
              width = 40,
              height = 144,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1661,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2248,
              y = 4088,
              width = 16,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1705,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2096,
              y = 4024,
              width = 56,
              height = 16,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1722,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2408,
              y = 4184,
              width = 40,
              height = 24,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1747,
              name = "",
              type = "",
              shape = "rectangle",
              x = 2840,
              y = 4000,
              width = 128,
              height = 368,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 1906,
              name = "",
              type = "",
              shape = "rectangle",
              x = 3008,
              y = 4240,
              width = 32,
              height = 128,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        }
      }
    }
  }
}
