return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "left-down",
  width = 256,
  height = 256,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 78,
  nextobjectid = 2131,
  properties = {},
  tilesets = {
    {
      name = "imgs",
      firstgid = 1,
      class = "",
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "imgs2",
      firstgid = 4,
      class = "",
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "xgame_bg",
      firstgid = 124,
      class = "",
      tilewidth = 393,
      tileheight = 359,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 6,
      tiles = {
        {
          id = 0,
          image = "gfx/levelAb_01.png",
          width = 44,
          height = 111
        },
        {
          id = 1,
          image = "gfx/levelAb_02.png",
          width = 149,
          height = 120
        },
        {
          id = 2,
          image = "gfx/levelAb_03.png",
          width = 184,
          height = 55
        },
        {
          id = 3,
          image = "gfx/levelAb_04.png",
          width = 393,
          height = 257
        },
        {
          id = 4,
          image = "gfx/levelAb_05.png",
          width = 383,
          height = 359
        },
        {
          id = 5,
          image = "gfx/levelAb_06.png",
          width = 241,
          height = 208
        }
      }
    },
    {
      name = "imgs3",
      firstgid = 130,
      class = "",
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "imgs4",
      firstgid = 147,
      class = "",
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "xgame_fg",
      firstgid = 174,
      class = "",
      tilewidth = 1049,
      tileheight = 448,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 2,
      tiles = {
        {
          id = 0,
          image = "gfx/levelAb_fg_01.png",
          width = 1049,
          height = 448
        },
        {
          id = 1,
          image = "gfx/levelAb_fg_02.png",
          width = 156,
          height = 168
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 25,
      name = "bg_deco_shapes_sky",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 70, 209 },
      properties = {},
      objects = {
        {
          id = 1253,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1968,
          y = 4000,
          width = 1024,
          height = 512,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2036,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2992,
          y = 4000,
          width = 1024,
          height = 512,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2060,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4016,
          y = 4000,
          width = 1024,
          height = 512,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2061,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5040,
          y = 4000,
          width = 1024,
          height = 512,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 57,
      name = "bg_deco_shapes_shadows",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 65,
      name = "bg_deco_shapes_lights",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 55,
      name = "bg_deco_shapes02",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 56,
      name = "bg_deco_shapes",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "group",
      id = 77,
      name = "***DECO OTHERS***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 73,
      name = "bg_deco_images_finalx",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3048,
          y = 4336,
          width = 44,
          height = 111,
          rotation = 0,
          gid = 124,
          visible = true,
          properties = {}
        },
        {
          id = 2123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3208,
          y = 4312,
          width = 149,
          height = 120,
          rotation = 0,
          gid = 125,
          visible = true,
          properties = {}
        },
        {
          id = 2124,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3456,
          y = 4312,
          width = 184,
          height = 55,
          rotation = 0,
          gid = 126,
          visible = true,
          properties = {}
        },
        {
          id = 2125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3656,
          y = 4304,
          width = 393,
          height = 257,
          rotation = 0,
          gid = 127,
          visible = true,
          properties = {}
        },
        {
          id = 2126,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4049,
          y = 4320,
          width = 383,
          height = 359,
          rotation = 0,
          gid = 128,
          visible = true,
          properties = {}
        },
        {
          id = 2127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4432,
          y = 4336,
          width = 241,
          height = 208,
          rotation = 0,
          gid = 129,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 58,
      name = "bg_deco_images_final",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 75,
      name = "fg_deco_images_finalx",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 74,
      name = "fg_deco_images_final",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2129,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1968,
          y = 4512,
          width = 1049,
          height = 448,
          rotation = 0,
          gid = 174,
          visible = true,
          properties = {}
        },
        {
          id = 2130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3320,
          y = 4296,
          width = 156,
          height = 168,
          rotation = 0,
          gid = 175,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 76,
      name = "***DECO FINAL***",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 66,
      name = "bg_deco_images04x",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 67,
      name = "bg_deco_images04",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 42,
      name = "bg_deco_images03x",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 63,
      name = "bg_deco_images03",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 64,
      name = "bg_deco_images02x",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 41,
      name = "bg_deco_images02",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 69,
      name = "bg_deco_imagesx",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 29,
      name = "bg_deco_images",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 32,
      name = "bg_deco_texts",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 255, 0 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 28,
      name = "fg_deco_shapes",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 255, 255 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 60,
      name = "fg_deco_images03",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 59,
      name = "fg_deco_images02",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 70,
      name = "fg_deco_imagesx",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 30,
      name = "fg_deco_images",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 33,
      name = "fg_deco_texts",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 255, 0 },
      properties = {},
      objects = {
        {
          id = 1106,
          name = "",
          type = "",
          shape = "text",
          x = 5376,
          y = 4208,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          text = "EXIT",
          fontfamily = "Segoe UI",
          pixelsize = 17,
          wrap = true,
          halign = "center",
          valign = "center",
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 48,
      name = "***DECO***",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 24,
      name = "physics_players",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 0, 0 },
      properties = {},
      objects = {
        {
          id = 654,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2032,
          y = 4168,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 72,
      name = "physics_npcs",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4360,
          y = 4224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 52,
      name = "physics_ground_nmes",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1382,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6064,
          y = 4256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 71,
      name = "physics_ground_boss1",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2067,
          name = "boss",
          type = "",
          shape = "rectangle",
          x = 2592,
          y = 4096,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2068,
          name = "boss",
          type = "",
          shape = "rectangle",
          x = 2400,
          y = 4096,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2069,
          name = "boss",
          type = "",
          shape = "rectangle",
          x = 2784,
          y = 4096,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 19,
      name = "physics_ground_nmes02",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 0, 0 },
      properties = {},
      objects = {
        {
          id = 1285,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5928,
          y = 4128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 47,
      name = "physics_ground_nmes03",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1291,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5928,
          y = 4008,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1300,
          name = "lives",
          type = "",
          shape = "rectangle",
          x = 6064,
          y = 4128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1364,
          name = "kdoorBb",
          type = "",
          shape = "rectangle",
          x = 6072,
          y = 3904,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 54,
      name = "physics_ground_nmes04",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1378,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5920,
          y = 3904,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1379,
          name = "kdoorCc",
          type = "",
          shape = "rectangle",
          x = 6072,
          y = 4016,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 23,
      name = "physics_flying_nmes",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 85, 0 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 39,
      name = "physics_turret_nmes",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 85, 0 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 43,
      name = "physics_breakables",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "group",
      id = 49,
      name = "***PHYSICS_ACTORS***",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 21,
      name = "physics_lives",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 170, 0 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 20,
      name = "physics_coins",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 170, 0 },
      properties = {},
      objects = {
        {
          id = 1383,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5928,
          y = 4264,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 38,
      name = "physics_keys",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 170, 127 },
      properties = {},
      objects = {
        {
          id = 1160,
          name = "kdoorAa",
          type = "",
          shape = "rectangle",
          x = 6248,
          y = 3720,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 50,
      name = "***PHYSICS_COLLECTIBLES***",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 61,
      name = "physics_grounds02",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "physics_grounds",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 53, 53, 53 },
      properties = {},
      objects = {
        {
          id = 1999,
          name = "a",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 4272,
          width = 1152,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2051,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3016,
          y = 4280,
          width = 88,
          height = 232,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2052,
          name = "a",
          type = "",
          shape = "rectangle",
          x = 3200,
          y = 4296,
          width = 2176,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2053,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3200,
          y = 4304,
          width = 2176,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2057,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 4000,
          width = 32,
          height = 512,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2059,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5664,
          y = 4408,
          width = 1248,
          height = 600,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 62,
      name = "physics_ptpfs02",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1788,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6072,
          y = 3624,
          width = 80,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "physics_ptpfs",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 85, 255 },
      properties = {},
      objects = {
        {
          id = 1762,
          name = "a",
          type = "",
          shape = "rectangle",
          x = 5968,
          y = 4344,
          width = 354,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "physics_steps",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 79, 238 },
      properties = {},
      objects = {
        {
          id = 1369,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4392,
          y = 4076,
          width = 4,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 22,
      name = "physics_walls",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 255, 0 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "physics_ladders",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 71, 71, 213 },
      properties = {},
      objects = {
        {
          id = 739,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6088,
          y = 3624,
          width = 48,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 17,
      name = "physics_mvpfs",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 85, 127 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 35,
      name = "physics_ptmvpfs",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 85, 127 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "physics_springs",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 170, 127 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 44,
      name = "physics_door_sensors",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 170, 255 },
      properties = {},
      objects = {
        {
          id = 1116,
          name = "kdoorZ1",
          type = "",
          shape = "rectangle",
          x = 5824,
          y = 3632,
          width = 208,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1118,
          name = "kdoorAa",
          type = "",
          shape = "rectangle",
          x = 6312,
          y = 3648,
          width = 224,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6032,
          y = 3632,
          width = 8,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5816,
          y = 3632,
          width = 8,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6304,
          y = 3648,
          width = 8,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6536,
          y = 3576,
          width = 8,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1221,
          name = "kdoorBb",
          type = "",
          shape = "rectangle",
          x = 6168,
          y = 3840,
          width = 256,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1222,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6424,
          y = 3840,
          width = 8,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1223,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6160,
          y = 3840,
          width = 8,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1246,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6416,
          y = 3976,
          width = 8,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1247,
          name = "kdoorZ3",
          type = "",
          shape = "rectangle",
          x = 6176,
          y = 3976,
          width = 240,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1249,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6168,
          y = 3976,
          width = 8,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1387,
          name = "kdoorCc",
          type = "",
          shape = "rectangle",
          x = 6176,
          y = 4168,
          width = 128,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1388,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6168,
          y = 4168,
          width = 8,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 37,
      name = "physics_doorsB",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 64, 62, 43 },
      properties = {},
      objects = {
        {
          id = 1220,
          name = "kdoorBbx0y72",
          type = "",
          shape = "rectangle",
          x = 6276,
          y = 3832,
          width = 24,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1248,
          name = "kdoorZ3x0y72",
          type = "",
          shape = "rectangle",
          x = 6280,
          y = 4016,
          width = 20,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1389,
          name = "kdoorCcx0y72",
          type = "",
          shape = "rectangle",
          x = 6304,
          y = 4192,
          width = 32,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 68,
      name = "physics_doors",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1893,
          name = "kdoorZ1x0y72",
          type = "",
          shape = "rectangle",
          x = 5920,
          y = 3680,
          width = 24,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1894,
          name = "kdoorAax0y72",
          type = "",
          shape = "rectangle",
          x = 6412,
          y = 3672,
          width = 24,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 40,
      name = "physics_spikes",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 255, 0, 0, 5 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 27,
      name = "physics_voids",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 0, 255 },
      properties = {},
      objects = {
        {
          id = 2054,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3200,
          y = 4512,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2055,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3072,
          y = 4640,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2056,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3072,
          y = 4512,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 31,
      name = "physics_exits",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 255, 255, 0 },
      properties = {},
      objects = {
        {
          id = 707,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5376,
          y = 4000,
          width = 32,
          height = 512,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 46,
      name = "physics_invisible_blocks",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 255, 170, 255 },
      properties = {},
      objects = {
        {
          id = 1297,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6266,
          y = 3984,
          width = 48,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 51,
      name = "***PHYSICS_WORLD***",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 45,
      name = "physics_map_def",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1172,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1968,
          y = 4000,
          width = 3408,
          height = 512,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 53,
      name = "***REFS***",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 26,
          name = "physics_mvpfs_REFS",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          tintcolor = { 255, 255, 255 },
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 36,
          name = "level_design_REFS",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 868,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1832,
              y = 4064,
              width = 32,
              height = 448,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        }
      }
    }
  }
}
